Updated to version 10
Updated libraries.
uploaded simpletest for sd card from library.
Sill get File "sd_read_simpletest.py", line 28, in <module>
RuntimeError: Mount point directory missing